<?php
/*
 * Evo-CMS
 * Copyright (c) 2014, Alex Duchesne <alex@alexou.net>.
 *
 * Licensed under the MIT license:
 * 	http://opensource.org/licenses/MIT
 */

 /*
define('EVO_RELEASEDATE', '2015-03-01');
define('ROOT_DIR', realpath(__DIR__.'/..'));
*/

require_once 'version.php';

defined('ROOT_DIR') or define('ROOT_DIR', realpath(__DIR__.'/..'));

define('PREG_USERNAME', '/^[-a-z0-9_][-a-z0-9_\. ]*[-a-z0-9_]$/i');
define('PREG_FILENAME', '#^[-a-z0-9_\. ]+$#i');
define('PREG_FILEPATH', '#^[-a-z0-9_\./ ]+$#i');
define('PREG_DIRNAME', '#^[-a-z0-9_\./ ]+$#i');
define('PREG_PASSWORD', '/^.{4,}$/');
define('PREG_EMAIL', '#^[a-z0-9][-a-z0-9_\.]+@[-a-z0-9_\.]+$#i');
define('PREG_DIGIT', '#^[0-9]+$#');
define('PREG_ALPHA', '#^[a-z]+$#i');
define('PREG_URL', '`^https?://[-A-Za-z0-9+&@/%?=~_#\.]+$`');

define('MSG_NORMAL', 0);
define('MSG_NOTIFICATION', 1);
define('MSG_IMPORTANT', 2);
define('MSG_WARNING', 3);


define('EVO_UPDATE_URL', '');


$_default_settings = [
	'articles_per_page' => 4,
	'open_registration' => 1,
	'change_theme' => 0,
	'default_user_group' => 3,
	'community_type' => 'generic',
	'frontpage' => 'home',
	'theme' => 'default',
	'plugins' => [],
	'editor' => 'html',
	'url' => '/',
	'base' => '/',
	'timezone' => '',
	'upload_groups' =>
		"image     jpg gif png bmp\n".
		"audio     wav mp3 wma ogg audio/midi\n".
		"video     avi wmv mp4 mpeg flv mkv webm\n".
		"archive   zip rar jar gz bz2 7z xz\n".
		"file      txt diff\n".
		"document  pdf doc docx xlsx xls csv odt ott oth odm",
];


$_groups = [
	1 => 'Administrator',
	2 => 'Moderator',
	3 => 'Member',
	4 => 'Guest',
];


$_communities = [
	'minecraft' => [
		'label' => 'Minecraft',
		'ingame_label' => 'Nom de compte Minecraft',
		'ingame_pattern' => PREG_USERNAME,
		'icon' => 'gamepad',
		'avatar' => function($user) {
			return 'https://minotar.net/avatar/' . urlencode($user) . '.png';
		},
	],
	'steam' => [
		'label' => 'Steam',
		'icon' => 'steam-square',
		'ingame_label' => 'Nom de compte Steam',
		'ingame_pattern' => PREG_USERNAME,
	],
];


$_message_type = [
		MSG_NORMAL       => ['message', '', 'fa-envelope', 'fa-folder-open-o', 'info'],
		MSG_NOTIFICATION => ['notification', '<span class="label label-info">Notification</span><br>', 'fa-bell', 'fa-bell-o', 'info'],
		MSG_IMPORTANT    => ['message important', '<span class="label label-warning">Important</span><br>', 'fa-exclamation', 'fa-folder-open-o', 'danger'],
		MSG_WARNING      => ['avertissement', '<span class="label label-danger">Avertissement</span><br>', 'fa-flag', 'fa-flag-o', 'danger'],
];


$_editors = [
	'html' => 'HTML (CKEditor)',
	'markdown' => 'Markdown+',
	'bbcode' => 'BBCode',
	'html-basic' => 'HTML (Basic)',
];

$_privileges = [
	'user' => [
		'label' => 'Membre',

		'Droits Généraux'=> [
			'view_uprofile' => 'Voir les profils des membres',
			'comment_send' => 'Poster des commentaires',
			'upload' => 'Uploader des fichiers (forum/avatar/etc)',
			'raf' => 'Parrainer un nouveau membre',
			],
		'Gestion des amis'=> [
			'view_friendlist' => 'Voir sa liste d\'amis',
			'be_friend' => 'Envoyer des demandes d\'ami',
			],
		'La Messagerie privé'=> [
			'send_pmess_friend' => 'Envoyer des messages privé à ses amis',
			'send_pmess_nofriend' => 'Envoyer des messages aux innamicaux',
			],
		'Situation'=> [
			'staff' => 'Est membre du staff',
			],
	],

	'mod' => [
		'label' => 'Modération',

		'Les Rapport'=> [
			'report_mess' => 'Message rapporté',
			'report_profile' => 'Profil rapporté',
			'report_post' => 'Commentaire rapporté',
			],

		'Les Articles'=> [
			'comment_delete' => 'Supprimer des commentaires',
			'comment_censure' => 'Censurer des commentaires',
			],

		'Gestion des membres'=> [
			'ban_member' => 'Suspension de compte',
			],

		'Forums'=> [
			'forum_topic_close' => 'Fermer des discussions',
			'forum_topic_stick' => 'Épingler des discussions',
			'forum_topic_move' => 'Déplacer des discussions',
			'forum_topic_delete' => 'Supprimer des discussions',
			'forum_topic_redirect' => 'Redirection de topic',
			'forum_post_delete' => 'Supprimer des messages',
			'forum_post_edit' => 'Éditer des messages',
			],
	],


	'admin' => [
		'label' => 'Administration',

		'Général'=> [
			'change_serv' => 'Ajout / Suppression d\'un serveur',
			'rcon' => 'Gestion RCON d\'un serveur',
			'change_website' => 'Modifier les informations du site',
			'backup_sql' => 'Téléchargement de la backup SQL',
			'download_bkp_web' => 'Téléchargement de la backup Web',
			'sql' => 'Gestion SQL',
			],

		'Contenu'=> [
			'page_create' => 'Créer des pages/articles',
			'page_edit' => 'Editer des pages/articles',
			'page_delete' => 'Supprimer des pages/articles',
			'edit_menu' => 'Modifier le menu',
			'media' => 'Gérer les fichiers médias',
			'upload_anything' => 'Uploader tout type de fichier (sauf php)',
			],

		'Communauté'=> [
			'forum_edit' => 'Gestion des forums',
			'poll_edit' => 'Gestion des sondages',
			'broadcast' => 'Envoi de mail de groupe',
			],

		'Gestion des membres'=> [
			'change_group' => 'Modifier les groupes',
			'add_member' => 'Ajouter un membre',
			'del_member' => 'Supprimer un membre',
			'edit_ugroup' => 'Changement de groupe',
			'edit_ingame' => 'Edition des noms ingame',
			'edit_raf' => 'Edition du parrain',
			'edit_uprofile' => 'Edition des profils',
			'receive_mess' => 'Message Reçus',
			'sending_mess' => 'Message Envoyés',
			],
		'Les Historiques'=> [
			'log_admin' => 'Administration',
			'log_user' => 'Historique membres',
			'log_pmail' => 'Messagerie Privé',
			'log_system' => 'Log Système',
			'log_forum' => 'Log Forum',
			],
	],
];



$_couleurs = [
	'BLACK' => '#000',
	'DARK_BLUE' => '#0000aa',
	'DARK_GREEN' => '#00aa00',
	'DARK_AQUA' => '#00aaaa',
	'DARK_RED' => '#aa0000',
	'DARK_PURPLE' => '#aa00aa',
	'GOLD' => '#ffaa00',
	'GRAY' => '#aaaaaa',
	'DARK_GRAY' => '#555555',
	'BLUE' => '#5555ff',
	'GREEN' => '#55ff55',
	'AQUA' => '#55ffff',
	'RED' => '#ff5555',
	'LIGHT_PURPLE' => '#ff55ff',
	'YELLOW' => '#ffff55',
];



$_emoticons = [
	':)' => 'smile.png',
	'8-)' => 'cool.png',
	':\'(' => 'cwy.png',
	':D' => 'grin.png',
	'<3' => 'heart.png',
	':(' => 'sad.png',
	':O' => 'shocked.png',
	':P' => 'tongue.png',
	';)' => 'wink.png',
	':ermm:' => 'ermm.png',
	':angel:' => 'angel.png',
	':angry:' => 'angry.png',
	':alien:' => 'alien.png',
	':blink:' => 'blink.png',
	':blush:' => 'blush.png',
	':cheerful:' => 'cheerful.png',
	':devil:' => 'devil.png',
	':dizzy:' => 'dizzy.png',
	':getlost:' => 'getlost.png',
	':happy:' => 'happy.png',
	':kissing:' => 'kissing.png',
	':ninja:' => 'ninja.png',
	':pinch:' => 'pinch.png',
	':pouty:' => 'pouty.png',
	':sick:' => 'sick.png',
	':sideways:' => 'sideways.png',
	':silly:' => 'silly.png',
	':sleeping:' => 'sleeping.png',
	':unsure:' => 'unsure.png',
	':woot:' => 'w00t.png',
	':wassat:' => 'wassat.png',
	':whistling:' => 'whistling.png',
	':love:' => 'wub.png',
	':pfff:' => 'pfff.png',
	':hmm:' => 'hmm.gif',
	':hihi:' => 'hihi.gif',
	':whistling:' => 'whistling.png',
	':love:' => 'wub.png',
	':bave:' => 'bave.gif',
	':mybad:' => 'mybad.png',
];


$_emoticons_hidden = [];


$_countries = [
	'' =>	'',
	'AF' =>	'Afganistan',
	'AL' =>	'Albania',
	'DZ' =>	'Algeria',
	'AS' => 'American Samoa',
	'AD' => 'Andorra',
	'AO' => 'Angola',
	'AI' => 'Anguilla',
	'AQ' => 'Antarctica',
	'AG' => 'Antigua and Barbuda',
	'AR' => 'Argentina',
	'AM' => 'Armenia',
	'AW' => 'Aruba',
	'AU' => 'Australia',
	'AT' => 'Austria',
	'AZ' => 'Azerbaijan',
	'BS' => 'Bahamas',
	'BH' => 'Bahrain',
	'BD' => 'Bangladesh',
	'BB' => 'Barbados',
	'BY' => 'Belarus',
	'BE' => 'Belgium',
	'BZ' => 'Belize',
	'BJ' => 'Benin',
	'BM' => 'Bermuda',
	'BT' => 'Bhutan',
	'BO' => 'Bolivia',
	'BA' => 'Bosnia and Herzegowina',
	'BW' => 'Botswana',
	'BV' => 'Bouvet Island',
	'BR' => 'Brazil',
	'IO' => 'British Indian Ocean Territory',
	'BN' => 'Brunei Darussalam',
	'BG' => 'Bulgaria',
	'BF' => 'Burkina Faso',
	'BI' => 'Burundi',
	'KH' => 'Cambodia',
	'CM' => 'Cameroon',
	'CA' => 'Canada',
	'CV' => 'Cape Verde',
	'KY' => 'Cayman Islands',
	'CF' => 'Central African Republic',
	'TD' => 'Chad',
	'CL' => 'Chile',
	'CN' => 'China',
	'CX' => 'Christmas Island',
	'CC' => 'Cocos (Keeling) Islands',
	'CO' => 'Colombia',
	'KM' => 'Comoros',
	'CG' => 'Congo',
	'CD' => 'Congo, the Democratic Republic of the',
	'CK' => 'Cook Islands',
	'CR' => 'Costa Rica',
	'CI' => 'Cote d\'Ivoire',
	'HR' => 'Croatia (Hrvatska)',
	'CU' => 'Cuba',
	'CY' => 'Cyprus',
	'CZ' => 'Czech Republic',
	'DK' => 'Denmark',
	'DJ' => 'Djibouti',
	'DM' => 'Dominica',
	'DO' => 'Dominican Republic',
	'TP' => 'East Timor',
	'EC' => 'Ecuador',
	'EG' => 'Egypt',
	'SV' => 'El Salvador',
	'GQ' => 'Equatorial Guinea',
	'ER' => 'Eritrea',
	'EE' => 'Estonia',
	'ET' => 'Ethiopia',
	'FK' => 'Falkland Islands (Malvinas)',
	'FO' => 'Faroe Islands',
	'FJ' => 'Fiji',
	'FI' => 'Finland',
	'FR' => 'France',
	'FX' => 'France, Metropolitan',
	'GF' => 'French Guiana',
	'PF' => 'French Polynesia',
	'TF' => 'French Southern Territories',
	'GA' => 'Gabon',
	'GM' => 'Gambia',
	'GE' => 'Georgia',
	'DE' => 'Germany',
	'GH' => 'Ghana',
	'GI' => 'Gibraltar',
	'GR' => 'Greece',
	'GL' => 'Greenland',
	'GD' => 'Grenada',
	'GP' => 'Guadeloupe',
	'GU' => 'Guam',
	'GT' => 'Guatemala',
	'GN' => 'Guinea',
	'GW' => 'Guinea-Bissau',
	'GY' => 'Guyana',
	'HT' => 'Haiti',
	'HM' => 'Heard and Mc Donald Islands',
	'VA' => 'Holy See (Vatican City State)',
	'HN' => 'Honduras',
	'HK' => 'Hong Kong',
	'HU' => 'Hungary',
	'IS' => 'Iceland',
	'IN' => 'India',
	'ID' => 'Indonesia',
	'IR' => 'Iran (Islamic Republic of)',
	'IQ' => 'Iraq',
	'IE' => 'Ireland',
	'IL' => 'Israel',
	'IT' => 'Italy',
	'JM' => 'Jamaica',
	'JP' => 'Japan',
	'JO' => 'Jordan',
	'KZ' => 'Kazakhstan',
	'KE' => 'Kenya',
	'KI' => 'Kiribati',
	'KP' => 'Korea, Democratic People\'s Republic of',
	'KR' => 'Korea, Republic of',
	'KW' => 'Kuwait',
	'KG' => 'Kyrgyzstan',
	'LA' => 'Lao People\'s Democratic Republic',
	'LV' => 'Latvia',
	'LB' => 'Lebanon',
	'LS' => 'Lesotho',
	'LR' => 'Liberia',
	'LY' => 'Libyan Arab Jamahiriya',
	'LI' => 'Liechtenstein',
	'LT' => 'Lithuania',
	'LU' => 'Luxembourg',
	'MO' => 'Macau',
	'MK' => 'Macedonia, The Former Yugoslav Republic of',
	'MG' => 'Madagascar',
	'MW' => 'Malawi',
	'MY' => 'Malaysia',
	'MV' => 'Maldives',
	'ML' => 'Mali',
	'MT' => 'Malta',
	'MH' => 'Marshall Islands',
	'MQ' => 'Martinique',
	'MR' => 'Mauritania',
	'MU' => 'Mauritius',
	'YT' => 'Mayotte',
	'MX' => 'Mexico',
	'FM' => 'Micronesia, Federated States of',
	'MD' => 'Moldova, Republic of',
	'MC' => 'Monaco',
	'MN' => 'Mongolia',
	'MS' => 'Montserrat',
	'MA' => 'Morocco',
	'MZ' => 'Mozambique',
	'MM' => 'Myanmar',
	'NA' => 'Namibia',
	'NR' => 'Nauru',
	'NP' => 'Nepal',
	'NL' => 'Netherlands',
	'AN' => 'Netherlands Antilles',
	'NC' => 'New Caledonia',
	'NZ' => 'New Zealand',
	'NI' => 'Nicaragua',
	'NE' => 'Niger',
	'NG' => 'Nigeria',
	'NU' => 'Niue',
	'NF' => 'Norfolk Island',
	'MP' => 'Northern Mariana Islands',
	'NO' => 'Norway',
	'OM' => 'Oman',
	'PK' => 'Pakistan',
	'PW' => 'Palau',
	'PA' => 'Panama',
	'PG' => 'Papua New Guinea',
	'PY' => 'Paraguay',
	'PE' => 'Peru',
	'PH' => 'Philippines',
	'PN' => 'Pitcairn',
	'PL' => 'Poland',
	'PT' => 'Portugal',
	'PR' => 'Puerto Rico',
	'QA' => 'Qatar',
	'RE' => 'Reunion',
	'RO' => 'Romania',
	'RU' => 'Russian Federation',
	'RW' => 'Rwanda',
	'KN' => 'Saint Kitts and Nevis',
	'LC' => 'Saint LUCIA',
	'VC' => 'Saint Vincent and the Grenadines',
	'WS' => 'Samoa',
	'SM' => 'San Marino',
	'ST' => 'Sao Tome and Principe',
	'SA' => 'Saudi Arabia',
	'SN' => 'Senegal',
	'SC' => 'Seychelles',
	'SL' => 'Sierra Leone',
	'SG' => 'Singapore',
	'SK' => 'Slovakia (Slovak Republic)',
	'SI' => 'Slovenia',
	'SB' => 'Solomon Islands',
	'SO' => 'Somalia',
	'ZA' => 'South Africa',
	'GS' => 'South Georgia and the South Sandwich Islands',
	'ES' => 'Spain',
	'LK' => 'Sri Lanka',
	'SH' => 'St. Helena',
	'PM' => 'St. Pierre and Miquelon',
	'SD' => 'Sudan',
	'SR' => 'Suriname',
	'SJ' => 'Svalbard and Jan Mayen Islands',
	'SZ' => 'Swaziland',
	'SE' => 'Sweden',
	'CH' => 'Switzerland',
	'SY' => 'Syrian Arab Republic',
	'TW' => 'Taiwan, Province of China',
	'TJ' => 'Tajikistan',
	'TZ' => 'Tanzania, United Republic of',
	'TH' => 'Thailand',
	'TG' => 'Togo',
	'TK' => 'Tokelau',
	'TO' => 'Tonga',
	'TT' => 'Trinidad and Tobago',
	'TN' => 'Tunisia',
	'TR' => 'Turkey',
	'TM' => 'Turkmenistan',
	'TC' => 'Turks and Caicos Islands',
	'TV' => 'Tuvalu',
	'UG' => 'Uganda',
	'UA' => 'Ukraine',
	'AE' => 'United Arab Emirates',
	'GB' => 'United Kingdom',
	'US' => 'United States',
	'UM' => 'United States Minor Outlying Islands',
	'UY' => 'Uruguay',
	'UZ' => 'Uzbekistan',
	'VU' => 'Vanuatu',
	'VE' => 'Venezuela',
	'VN' => 'Viet Nam',
	'VG' => 'Virgin Islands (British)',
	'VI' => 'Virgin Islands (U.S.)',
	'WF' => 'Wallis and Futuna Islands',
	'EH' => 'Western Sahara',
	'YE' => 'Yemen',
	'YU' => 'Yugoslavia',
	'ZM' => 'Zambia',
	'ZW' => 'Zimbabwe'
];



# Took and reformated from http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html #
$_timezones = [
	// 'Server default'              =>  '',
	'International Date Line West'=> 'Pacific/Midway',
	'Midway Island'               => 'Pacific/Midway',
	'American Samoa'              => 'Pacific/Pago_Pago',
	'Hawaii'                      => 'Pacific/Honolulu',
	'Alaska'                      => 'America/Juneau',
	'Pacific Time (US & Canada)'  => 'America/Los_Angeles',
	'Tijuana'                     => 'America/Tijuana',
	'Mountain Time (US & Canada)' => 'America/Denver',
	'Arizona'                     => 'America/Phoenix',
	'Chihuahua'                   => 'America/Chihuahua',
	'Mazatlan'                    => 'America/Mazatlan',
	'Central Time (US & Canada)'  => 'America/Chicago',
	'Saskatchewan'                => 'America/Regina',
	'Guadalajara'                 => 'America/Mexico_City',
	'Mexico City'                 => 'America/Mexico_City',
	'Monterrey'                   => 'America/Monterrey',
	'Central America'             => 'America/Guatemala',
	'Eastern Time (US & Canada)'  => 'America/New_York',
	'Indiana (East)'              => 'America/Indiana/Indianapolis',
	'Bogota'                      => 'America/Bogota',
	'Lima'                        => 'America/Lima',
	'Quito'                       => 'America/Lima',
	'Atlantic Time (Canada)'      => 'America/Halifax',
	'Caracas'                     => 'America/Caracas',
	'La Paz'                      => 'America/La_Paz',
	'Santiago'                    => 'America/Santiago',
	'Newfoundland'                => 'America/St_Johns',
	'Brasilia'                    => 'America/Sao_Paulo',
	'Buenos Aires'                => 'America/Argentina/Buenos_Aires',
	'Montevideo'                  => 'America/Montevideo',
	'Georgetown'                  => 'America/Guyana',
	'Greenland'                   => 'America/Godthab',
	'Mid-Atlantic'                => 'Atlantic/South_Georgia',
	'Azores'                      => 'Atlantic/Azores',
	'Cape Verde Is.'              => 'Atlantic/Cape_Verde',
	'Dublin'                      => 'Europe/Dublin',
	'Edinburgh'                   => 'Europe/London',
	'Lisbon'                      => 'Europe/Lisbon',
	'London'                      => 'Europe/London',
	'Casablanca'                  => 'Africa/Casablanca',
	'Monrovia'                    => 'Africa/Monrovia',
	'UTC'                         => 'Etc/UTC',
	'Belgrade'                    => 'Europe/Belgrade',
	'Bratislava'                  => 'Europe/Bratislava',
	'Budapest'                    => 'Europe/Budapest',
	'Ljubljana'                   => 'Europe/Ljubljana',
	'Prague'                      => 'Europe/Prague',
	'Sarajevo'                    => 'Europe/Sarajevo',
	'Skopje'                      => 'Europe/Skopje',
	'Warsaw'                      => 'Europe/Warsaw',
	'Zagreb'                      => 'Europe/Zagreb',
	'Brussels'                    => 'Europe/Brussels',
	'Copenhagen'                  => 'Europe/Copenhagen',
	'Madrid'                      => 'Europe/Madrid',
	'Paris'                       => 'Europe/Paris',
	'Amsterdam'                   => 'Europe/Amsterdam',
	'Berlin'                      => 'Europe/Berlin',
	'Bern'                        => 'Europe/Berlin',
	'Rome'                        => 'Europe/Rome',
	'Stockholm'                   => 'Europe/Stockholm',
	'Vienna'                      => 'Europe/Vienna',
	'West Central Africa'         => 'Africa/Algiers',
	'Bucharest'                   => 'Europe/Bucharest',
	'Cairo'                       => 'Africa/Cairo',
	'Helsinki'                    => 'Europe/Helsinki',
	'Kyiv'                        => 'Europe/Kiev',
	'Riga'                        => 'Europe/Riga',
	'Sofia'                       => 'Europe/Sofia',
	'Tallinn'                     => 'Europe/Tallinn',
	'Vilnius'                     => 'Europe/Vilnius',
	'Athens'                      => 'Europe/Athens',
	'Istanbul'                    => 'Europe/Istanbul',
	'Minsk'                       => 'Europe/Minsk',
	'Jerusalem'                   => 'Asia/Jerusalem',
	'Harare'                      => 'Africa/Harare',
	'Pretoria'                    => 'Africa/Johannesburg',
	'Moscow'                      => 'Europe/Moscow',
	'St. Petersburg'              => 'Europe/Moscow',
	'Volgograd'                   => 'Europe/Moscow',
	'Kuwait'                      => 'Asia/Kuwait',
	'Riyadh'                      => 'Asia/Riyadh',
	'Nairobi'                     => 'Africa/Nairobi',
	'Baghdad'                     => 'Asia/Baghdad',
	'Tehran'                      => 'Asia/Tehran',
	'Abu Dhabi'                   => 'Asia/Muscat',
	'Muscat'                      => 'Asia/Muscat',
	'Baku'                        => 'Asia/Baku',
	'Tbilisi'                     => 'Asia/Tbilisi',
	'Yerevan'                     => 'Asia/Yerevan',
	'Kabul'                       => 'Asia/Kabul',
	'Ekaterinburg'                => 'Asia/Yekaterinburg',
	'Islamabad'                   => 'Asia/Karachi',
	'Karachi'                     => 'Asia/Karachi',
	'Tashkent'                    => 'Asia/Tashkent',
	'Chennai'                     => 'Asia/Kolkata',
	'Kolkata'                     => 'Asia/Kolkata',
	'Mumbai'                      => 'Asia/Kolkata',
	'New Delhi'                   => 'Asia/Kolkata',
	'Kathmandu'                   => 'Asia/Kathmandu',
	'Astana'                      => 'Asia/Dhaka',
	'Dhaka'                       => 'Asia/Dhaka',
	'Sri Jayawardenepura'         => 'Asia/Colombo',
	'Almaty'                      => 'Asia/Almaty',
	'Novosibirsk'                 => 'Asia/Novosibirsk',
	'Rangoon'                     => 'Asia/Rangoon',
	'Bangkok'                     => 'Asia/Bangkok',
	'Hanoi'                       => 'Asia/Bangkok',
	'Jakarta'                     => 'Asia/Jakarta',
	'Krasnoyarsk'                 => 'Asia/Krasnoyarsk',
	'Beijing'                     => 'Asia/Shanghai',
	'Chongqing'                   => 'Asia/Chongqing',
	'Hong Kong'                   => 'Asia/Hong_Kong',
	'Urumqi'                      => 'Asia/Urumqi',
	'Kuala Lumpur'                => 'Asia/Kuala_Lumpur',
	'Singapore'                   => 'Asia/Singapore',
	'Taipei'                      => 'Asia/Taipei',
	'Perth'                       => 'Australia/Perth',
	'Irkutsk'                     => 'Asia/Irkutsk',
	'Ulaanbaatar'                 => 'Asia/Ulaanbaatar',
	'Seoul'                       => 'Asia/Seoul',
	'Osaka'                       => 'Asia/Tokyo',
	'Sapporo'                     => 'Asia/Tokyo',
	'Tokyo'                       => 'Asia/Tokyo',
	'Yakutsk'                     => 'Asia/Yakutsk',
	'Darwin'                      => 'Australia/Darwin',
	'Adelaide'                    => 'Australia/Adelaide',
	'Canberra'                    => 'Australia/Melbourne',
	'Melbourne'                   => 'Australia/Melbourne',
	'Sydney'                      => 'Australia/Sydney',
	'Brisbane'                    => 'Australia/Brisbane',
	'Hobart'                      => 'Australia/Hobart',
	'Vladivostok'                 => 'Asia/Vladivostok',
	'Guam'                        => 'Pacific/Guam',
	'Port Moresby'                => 'Pacific/Port_Moresby',
	'Magadan'                     => 'Asia/Magadan',
	'Solomon Is.'                 => 'Pacific/Guadalcanal',
	'New Caledonia'               => 'Pacific/Noumea',
	'Fiji'                        => 'Pacific/Fiji',
	'Kamchatka'                   => 'Asia/Kamchatka',
	'Marshall Is.'                => 'Pacific/Majuro',
	'Auckland'                    => 'Pacific/Auckland',
	'Wellington'                  => 'Pacific/Auckland',
	'Nuku\'alofa'                 => 'Pacific/Tongatapu',
	'Tokelau Is.'                 => 'Pacific/Fakaofo',
	'Chatham Is.'                 => 'Pacific/Chatham',
	'Samoa'                       => 'Pacific/Apia'
];
